In [99]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns 
import ast

In [100]:
df=pd.read_csv("movies.csv")
print(df.columns)
df=df.drop(['Unnamed: 0'],axis=1)
df.head()

Index(['Unnamed: 0.1', 'Unnamed: 0', 'name', 'country', 'language', 'year',
       'director', 'cast', 'rating', 'genre', 'rating_count', 'duration',
       'description', 'image'],
      dtype='object')

,Unnamed: 0.1,name,country,language,year,director,cast,rating,genre,rating_count,duration,description,image
0,0,The Shawshank Redemption,United States,English,1994,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton']",9.3,Drama,2949951,2H22M,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...
1,1,The Godfather,United States,English,1972,Francis Ford Coppola,"['Mario Puzo', 'Francis Ford Coppola']",9.2,"Crime, Drama",2056341,2H55M,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BYTJkNG...
2,2,The Dark Knight,United States,Warner Bros.,2008,Christopher Nolan,"['Jonathan Nolan', 'Christopher Nolan', 'David...",9.0,"Action, Crime, Drama",2925228,2H32M,When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,3,The Godfather Part II,United States,English,1974,Francis Ford Coppola,"['Francis Ford Coppola', 'Mario Puzo']",9.0,"Crime, Drama",1389782,3H22M,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BNzc1OW...
4,4,12 Angry Men,United States,Orion-Nova Productions,1957,Sidney Lumet,['Reginald Rose'],9.0,"Crime, Drama",887543,1H36M,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...

In [101]:
df['country'].unique()
df['language'].unique()

array(['English', 'Warner Bros.', 'Orion-Nova Productions',
       'Official site: The Lord of the Rings Trilogy',
       'Official Facebook', 'Italian', 'Official Site',
       'Warner Bros. (United States)', 'Fantasy Films',
       'Pacific Electric Building, Los Angeles, California, USA',
       'French', 'Toho', 'Latin',
       'Official site (3D re-release) (Germany)', 'Miyazaki collection',
       'United Kingdom', 'Korean', 'Alfred J. Hitchcock Productions',
       'Morocco', 'Columbia Pictures', 'Cantonese', 'Shinchosha Company',
       'Durango and Silverton Narrow Gauge Railroad, Colorado, USA', nan,
       'Hungary', 'Official site', 'German', 'Hindi',
       'Paramount Pictures', 'Official Disney+ Hotstar',
       'Metro-Goldwyn-Mayer Studios - 10202 W. Washington Blvd., Culver City, California, USA',
       'Timberline Lodge, Mount Hood, Oregon, USA', 'HBOMAX',
       'Official site (Russia)', 'Busan, South Korea',
       'Sacramento, California, USA', 'DENTSU Music And Entertainment',
       'Japanese', 'Kurosawa Production Co.', "Loew's", 'Cyprus',
       'Artisan Entertainment', 'Official Facebook (United States)',
       '5860 North Figueroa Street, Highland Park, Los Angeles, California, USA',
       'The Mirisch Corporation',
       'Garces Highway 1/10th mile East from Corcoran Road and Kern National Wildlife Preserve, Kern County, California, USA',
       '6301 Quebec Drive, Hollywood Hills, Los Angeles, California, USA',
       'Official Instagram', 'Nero-Film AG',
       'Fort Point, Presidio, Golden Gate National Recreation Area, San Francisco, California, USA',
       'Vietnamese',
       'Binsey Walk, Southmere Lake, Thamesmead South, London, England, UK',
       'Monroeville, Alabama, USA', 'Golem Distribución (Spain)',
       'Zanuck/Brown Productions', 'Spain',
       'Frolic Room - 6245 Hollywood Blvd., Hollywood, Los Angeles, California, USA',
       'Citta Valmelaina, Via Salaria, Rome, Lazio, Italy',
       '87 Columbia Heights, Brooklyn, New York, USA',
       'Official Facebook (United Kingdom)', 'Ashton Productions',
       'former Reichsparteitag area, Nuremberg, Bavaria, Germany',
       'Facebook (United States)', 'Spanish',
       'Aso-Kuju National Park, Kumamoto, Japan',
       'Brooks, Alberta, Canada', 'Norwegian',
       'Kernville, California, USA', 'Daiei',
       'Selznick International Pictures',
       'Estación Retiro, Retiro, Buenos Aires, Federal District, Argentina',
       'Chartoff-Winkler Productions', 'Austria', 'Iceland',
       'Official site (Japan)', 'Instagram', 'Persian',
       "St. Andrew's School - 350 Noxontown Road, Middletown, Delaware, USA",
       'Universal Pictures Home Entertainment (United States)',
       'Buster Keaton Productions',
       "Water Street, Edgartown, Martha's Vineyard, Massachusetts, USA",
       'St Peter and St Paul Church - 400 Hudson Street, Hoboken, New Jersey, USA',
       'Tokyo, Japan', 'United States', '2D Entertainment',
       'Boulogne-Billancourt, Hauts-de-Seine, France',
       'The Samuel Goldwyn Company',
       'Stage 28, Sony Pictures Studios - 10202 W. Washington Blvd., Culver City, California, USA',
       'Metro-Goldwyn-Mayer (MGM)',
       'Eagle Mountain Ln, Burney, California, USA', 'Danish', 'Arabic',
       'Twentieth Century Fox',
       'Colonia Condesa, Mexico City, Distrito Federal, Mexico',
       'Big Sur, California, USA', 'Jalem Productions'], dtype=object)

In [102]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          250 non-null    object
 1   country       234 non-null    object
 2   language      233 non-null    object
 3   year          250 non-null    int64
 4   director      250 non-null    object
 5   cast          250 non-null    object
 6   rating        250 non-null    float64
 7   genre         250 non-null    object
 8   rating_count  250 non-null    int64
 9   duration      250 non-null    object
 10  description   250 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 21.6+ KB

DROP COLUMN LANGUAGE AS THIS DATA CONTAIN LOT OF IMPURITES THAT CANT BE HANDLE AND ALSO LANGUAGE IS SIMILAR TO COUNTRY, SO THESE BOTH CAN BE CONSIDERED AS SAME FEATURES

In [103]:
df_1=df.drop(['language'],axis=1)

In [104]:
df_1

,Unnamed: 0.1,name,country,year,director,cast,rating,genre,rating_count,duration,description,image
0,0,The Shawshank Redemption,United States,1994,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton']",9.3,Drama,2949951,2H22M,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...
1,1,The Godfather,United States,1972,Francis Ford Coppola,"['Mario Puzo', 'Francis Ford Coppola']",9.2,"Crime, Drama",2056341,2H55M,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BYTJkNG...
2,2,The Dark Knight,United States,2008,Christopher Nolan,"['Jonathan Nolan', 'Christopher Nolan', 'David...",9.0,"Action, Crime, Drama",2925228,2H32M,When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,3,The Godfather Part II,United States,1974,Francis Ford Coppola,"['Francis Ford Coppola', 'Mario Puzo']",9.0,"Crime, Drama",1389782,3H22M,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BNzc1OW...
4,4,12 Angry Men,United States,1957,Sidney Lumet,['Reginald Rose'],9.0,"Crime, Drama",887543,1H36M,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...
...,...,...,...,...,...,...,...,...,...,...,...,...
245,245,Cool Hand Luke,United States,1967,Stuart Rosenberg,"['Donn Pearce', 'Frank Pierson', 'Hal Dresner']",8.1,"Crime, Drama",191299,2H7M,A laid-back Southern man is sentenced to two y...,https://m.media-amazon.com/images/M/MV5BYzI1Nz...
246,246,It Happened One Night,United States,1934,Frank Capra,"['Clark Gable', 'Claudette Colbert', 'Walter C...",8.1,"Comedy, Romance",114437,1H45M,A rogue reporter trailing a runaway heiress fo...,https://m.media-amazon.com/images/M/MV5BOTYxYW...
247,247,Gangs of Wasseypur,India,2012,Anurag Kashyap,"['Akhilesh Jaiswal', 'Anurag Kashyap', 'Sachin...",8.2,"Action, Comedy, Crime",105645,5H21M,A clash between Sultan and Shahid Khan leads t...,https://m.media-amazon.com/images/M/MV5BMTc5Nj...
248,248,Drishyam,India,2015,Nishikant Kamat,"['Ajay Devgn', 'Shriya Saran', 'Tabu']",8.2,"Crime, Drama, Mystery",97800,2H43M,Desperate measures are taken by a man who trie...,https://m.media-amazon.com/images/M/MV5BM2NmMG...
249,249,"Paris, Texas",West Germany,1984,Wim Wenders,"['Harry Dean Stanton', 'Nastassja Kinski', 'De...",8.1,Drama,124610,2H25M,"Travis Henderson, an aimless drifter who has b...",https://m.media-amazon.com/images/M/MV5BMjZiYT...

In [105]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  250 non-null    int64
 1   name          250 non-null    object
 2   country       234 non-null    object
 3   year          250 non-null    int64
 4   director      250 non-null    object
 5   cast          250 non-null    object
 6   rating        250 non-null    float64
 7   genre         250 non-null    object
 8   rating_count  250 non-null    int64
 9   duration      250 non-null    object
 10  description   250 non-null    object
 11  image         250 non-null    object
dtypes: float64(1), int64(3), object(8)
memory usage: 23.6+ KB

In [106]:
df_1.head(5)

,Unnamed: 0.1,name,country,year,director,cast,rating,genre,rating_count,duration,description,image
0,0,The Shawshank Redemption,United States,1994,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton']",9.3,Drama,2949951,2H22M,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...
1,1,The Godfather,United States,1972,Francis Ford Coppola,"['Mario Puzo', 'Francis Ford Coppola']",9.2,"Crime, Drama",2056341,2H55M,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BYTJkNG...
2,2,The Dark Knight,United States,2008,Christopher Nolan,"['Jonathan Nolan', 'Christopher Nolan', 'David...",9.0,"Action, Crime, Drama",2925228,2H32M,When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,3,The Godfather Part II,United States,1974,Francis Ford Coppola,"['Francis Ford Coppola', 'Mario Puzo']",9.0,"Crime, Drama",1389782,3H22M,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BNzc1OW...
4,4,12 Angry Men,United States,1957,Sidney Lumet,['Reginald Rose'],9.0,"Crime, Drama",887543,1H36M,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...

CONVERTING THE DURATION COLUMN INTO MINUTES

In [107]:
def func(x):
    if ('H' in x) and ('M' in  x):
        a=int(x.split('H')[0])*60
        b=x.split('H')[1].split('M')[0].strip()
        if b=='':
            b=0
        else:
            b=int(x.split('H')[1].split('M')[0])
        return (a+b)
    elif 'H' in x:
        a=int(x.split('H')[0])*60
        return a
    else:
        b=int(x.split('M')[0])
        return b

df_1['duration']=df_1['duration'].apply(func)

In [108]:
df_1.head()

,Unnamed: 0.1,name,country,year,director,cast,rating,genre,rating_count,duration,description,image
0,0,The Shawshank Redemption,United States,1994,Frank Darabont,"['Tim Robbins', 'Morgan Freeman', 'Bob Gunton']",9.3,Drama,2949951,142,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...
1,1,The Godfather,United States,1972,Francis Ford Coppola,"['Mario Puzo', 'Francis Ford Coppola']",9.2,"Crime, Drama",2056341,175,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BYTJkNG...
2,2,The Dark Knight,United States,2008,Christopher Nolan,"['Jonathan Nolan', 'Christopher Nolan', 'David...",9.0,"Action, Crime, Drama",2925228,152,When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,3,The Godfather Part II,United States,1974,Francis Ford Coppola,"['Francis Ford Coppola', 'Mario Puzo']",9.0,"Crime, Drama",1389782,202,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BNzc1OW...
4,4,12 Angry Men,United States,1957,Sidney Lumet,['Reginald Rose'],9.0,"Crime, Drama",887543,96,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...

In [109]:
#df_1['cast'] = df_1['cast'].apply(lambda x: ', '.join(x))

NOW IMPROVINF CAST COLUMN CONVERTING IT TO CSV VALUES AND DOING SAME WITH GENRE COLUMN

In [110]:
# Convert the string representation of lists to actual lists
df_1['cast'] = df_1['cast'].apply(ast.literal_eval)

# Convert the cast lists to CSV format
df_1['cast'] = df_1['cast'].apply(lambda x: ', '.join(x))

In [111]:
df_1.head(5)

,Unnamed: 0.1,name,country,year,director,cast,rating,genre,rating_count,duration,description,image
0,0,The Shawshank Redemption,United States,1994,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton",9.3,Drama,2949951,142,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...
1,1,The Godfather,United States,1972,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola",9.2,"Crime, Drama",2056341,175,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BYTJkNG...
2,2,The Dark Knight,United States,2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",9.0,"Action, Crime, Drama",2925228,152,When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,3,The Godfather Part II,United States,1974,Francis Ford Coppola,"Francis Ford Coppola, Mario Puzo",9.0,"Crime, Drama",1389782,202,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BNzc1OW...
4,4,12 Angry Men,United States,1957,Sidney Lumet,Reginald Rose,9.0,"Crime, Drama",887543,96,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...

In [112]:
df_1['genre'].unique()[:5]

array(['Drama', 'Crime, Drama', 'Action, Crime, Drama',
       'Action, Adventure, Drama', 'Biography, Drama, History'],
      dtype=object)

In [113]:
df_1['genre'] = df_1['genre'].apply(lambda x: x.split(', '))

In [114]:
df_1['genre'] = df_1['genre'].apply(lambda x: ', '.join(x))

In [115]:
df_1.head()

,Unnamed: 0.1,name,country,year,director,cast,rating,genre,rating_count,duration,description,image
0,0,The Shawshank Redemption,United States,1994,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton",9.3,Drama,2949951,142,A banker convicted of uxoricide forms a friend...,https://m.media-amazon.com/images/M/MV5BMDAyY2...
1,1,The Godfather,United States,1972,Francis Ford Coppola,"Mario Puzo, Francis Ford Coppola",9.2,"Crime, Drama",2056341,175,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BYTJkNG...
2,2,The Dark Knight,United States,2008,Christopher Nolan,"Jonathan Nolan, Christopher Nolan, David S. Goyer",9.0,"Action, Crime, Drama",2925228,152,When a menace known as the Joker wreaks havoc ...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,3,The Godfather Part II,United States,1974,Francis Ford Coppola,"Francis Ford Coppola, Mario Puzo",9.0,"Crime, Drama",1389782,202,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BNzc1OW...
4,4,12 Angry Men,United States,1957,Sidney Lumet,Reginald Rose,9.0,"Crime, Drama",887543,96,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BYjE4Nz...

In [116]:
df_1.to_csv('IMDBcleaned.csv', index=False)